------------------------------------
-- ISIDRO ARREDONDO CAMARENA --
------------------------------------

CREATE OR REPLACE FUNCTION AFECTAR_INVENTARIO(_ID_DULCE NUMERIC, _CANTIDAD NUMERIC)
RETURNS BOOLEAN
AS
$$
--DECLARACIONES
	DECLARE
		_STOCK SMALLINT;
		
	--CUERPO 
	BEGIN
		RAISE NOTICE 'BIENVENIDO';
		--ASIGNARLE VALOR A LAS VARIABLES
		_STOCK:=NULL;

		--VERIFICAR SI EXISTE EL PRODUCTO
		IF EXISTS(SELECT 1 FROM DULCES WHERE ID_DULCE=_ID_DULCE)THEN 
			--RAISE NOTICE 'EL PRODUCTO EXISTE';
			SELECT _STOCK INTO _STOCK FROM DULCES WHERE ID_DULCE=_ID_DULCE;
			RAISE NOTICE 'EXISTENCIA % ' , _STOCK;
			--VERIFICAR QUE HAYA SUFICIENCIA EN INVENTARIO
			IF _STOCK<_CANTIDAD THEN 
				RAISE EXCEPTION 'NO HAY SUFICIENTE EN EXISTENCIA';
			END IF;
			--ACTUALIZAR EL INVENTARIO
				UPDATE DULCES SET STOCK = STOCK - _CANTIDAD WHERE ID_DULCE=_ID_DULCE;
				RAISE NOTICE 'TRUE';
				RETURN TRUE;
		ELSE
			RAISE NOTICE 'EL PRODUCTO % NO EXISTE' , _ID_DULCE;
			RETURN FALSE;
		END IF;
	END;
$$
LANGUAGE PLPGSQL; 

SELECT AFECTAR_INVENTARIO(1,6)

SELECT * FROM DULCES

-- CREAR EL REGISTRO DE LA VENTA
CREATE OR REPLACE PROCEDURE SP_REGISTRO_VENTAS ( _ID_USUARIO NUMERIC, 
_ID_SUCURSAL NUMERIC, _ID_DULCE NUMERIC, _CANTIDAD NUMERIC)
AS
$$
	DECLARE 
		_PRECIO_UNI NUMERIC;
		_DESCUENTO NUMERIC;
		_ID_VENTA  INT;
	BEGIN
	SELECT PRECIO_UNI INTO _PRECIO_UNI FROM DULCES WHERE ID_DULCE=_ID_DULCE;
	IF (_CANTIDAD > 20) THEN 
		_DESCUENTO := 10;
	ELSE IF (_CANTIDAD > 10) THEN 
		_DESCUENTO := 5;
	END IF;
	END IF;	
		-- VER SI EXISTE EL USUARIO 
		IF EXISTS(SELECT 1 FROM USUARIOS WHERE ID_USUARIO=_ID_USUARIO)THEN
			-- VER SI EXISTE LA SUCURSAL
			IF EXISTS(SELECT 1 FROM SUCURSALES WHERE ID_SUCURSAL=_ID_SUCURSAL)THEN
				--VER SI EXISTE EL DULCE
				IF EXISTS(SELECT 1 FROM DULCES WHERE ID_DULCE=_ID_DULCE)THEN
					-- OBTENER EL NUMERO DE VENTA
					SELECT MAX (ID_VENTA)+1 INTO _ID_VENTA FROM VENTAS;
					-- INSERTAR EL NUEVO REGISTRO DE VENTA
					INSERT INTO VENTAS VALUES
					(_ID_VENTA,_ID_USUARIO,_ID_SUCURSAL,_ID_DULCE,_CANTIDAD,CURRENT_DATE,_PRECIO_UNI,_DESCUENTO);
				ELSE
					RAISE NOTICE 'NO EXISTE EL DULCE %', _ID_DULCE;
				END IF;
			ELSE
				RAISE NOTICE 'NO EXISTE LA SUCURSAL %', _ID_SUCURSAL;
			END IF;
		ELSE
			RAISE NOTICE 'NO EXISTE EL USUARIO %', _ID_USUARIO;
		END IF;
	END;
$$
LANGUAGE PLPGSQL;

CALL SP_REGISTRO_VENTAS ( 1, 1, 1, 13)
SELECT * FROM VENTAS

CREATE OR REPLACE FUNCTION MOVIMIENTO_COMPLETO(_ID_USUARIO NUMERIC, 
_ID_SUCURSAL NUMERIC, _ID_DULCE NUMERIC, _CANTIDAD NUMERIC)
RETURNS TEXT
AS
$$
	DECLARE
	BAN BOOLEAN;
	BEGIN
		-- LLAMAR EL REGISTRO DE LA VENTA
		BAN:=TRUE;
		IF (BAN) THEN
			CALL SP_REGISTRO_VENTAS ( _ID_USUARIO, _ID_SUCURSAL, _ID_DULCE, _CANTIDAD);
			-- LLAMAR AL AFECTAR INVENTARIO
			PERFORM AFECTAR_INVENTARIO(_ID_DULCE,_CANTIDAD);
			RETURN 'EL MOVIMIENTO SE EFECTUO CON EXITO';
		ELSE
			RETURN 'EL MOVIMIENTO NO SE PUDO PROCESAR';
		END IF;
	END;
$$
LANGUAGE PLPGSQL;

SELECT MOVIMIENTO_COMPLETO ( 3, 4, 2, 14);



